const allProducts = [
  {
    category: "TOP",
    tooltip: "NEW",
    Dimage: "images/image_17.png",
    Himage: "images/image_18.png",
    name: "Mesh Shirt",
    oldPrice: "$55.00",
    newPrice: "$45.00",
    free: "18%",
  },
  {
    category: "TOP",
    tooltip: "SALE",
    Dimage: "images/15-1.webp",
    Himage: "images/image_16.png",
    name: "Off-The-Shoulder Blouse",
    oldPrice: "$32.00",
    newPrice: "$40.00",
    free: "20%",
  },
  {
    category: "TOP",
    tooltip: "SALE",
    Dimage: "images/16-1.webp",
    Himage: "images/image_14.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "9%",
  },
  {
    category: "TOP",
    tooltip: "SALE",
    Dimage: "images/20-1.webp",
    Himage: "images/image_13.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "9%",
  },

  {
    category: "T-SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_11.png",
    Himage: "images/image_12.png",
    name: "Mesh Shirt",
    oldPrice: "$55.00",
    newPrice: "$45.00",
    free: "18%",
  },
  {
    category: "T-SHIRT",
    tooltip: "SALE",
    Dimage: "images/image_13.png",
    Himage: "images/image_14.png",
    name: "Off-The-Shoulder Blouse",
    oldPrice: "$32.00",
    newPrice: "$40.00",
    free: "20%",
  },
  {
    category: "T-SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_15.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "9%",
  },
  {
    category: "T-SHIRT",
    tooltip: "SALE",
    Dimage: "images/image_17.png",
    Himage: "images/image_18.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "9%",
  },

  {
    category: "DRESS",
    tooltip: "SALE",
    Dimage: "images/image_25.png",
    Himage: "images/image_24.png",
    name: "Off-The-Shoulder Blouse",
    oldPrice: "$32.00",
    newPrice: "$40.00",
    free: "20%",
  },
  {
    category: "DRESS",
    tooltip: "NEW",
    Dimage: "images/image_23.png",
    Himage: "images/image_20.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "65%",
  },
  {
    category: "DRESS",
    tooltip: "SALE",
    Dimage: "images/image_20.png",
    Himage: "images/image_21.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "22%",
  },
  {
    category: "SETS",
    tooltip: "NEW",
    Dimage: "images/image_14.png",
    Himage: "images/image_15.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "3%",
  },
  {
    category: "SETS",
    tooltip: "SALE",
    Dimage: "images/image_17.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "01%",
  },

  {
    category: "SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_13.png",
    Himage: "images/image_14.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "54%",
  },
  {
    category: "SHIRT",
    tooltip: "SALE",
    Dimage: "images/image_25.png",
    Himage: "images/image_12.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "21%",
  },
  {
    category: "SETS",
    tooltip: "SALE",
    Dimage: "images/image_23.png",
    Himage: "images/image_21.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "24%",
  },
  {
    category: "T-SHIRT",
    tooltip: "SALE",
    Dimage: "images/image_13.png",
    Himage: "images/image_14.png",
    name: "Off-The-Shoulder Blouse",
    oldPrice: "$32.00",
    newPrice: "$40.00",
    free: "20%",
  },
  {
    category: "T-SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_15.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "9%",
  },
  {
    category: "SETS",
    tooltip: "SALE",
    Dimage: "images/image_17.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "01%",
  },
  {
    category: "TOP",
    tooltip: "NEW",
    Dimage: "images/image_17.png",
    Himage: "images/image_18.png",
    name: "Mesh Shirt",
    oldPrice: "$55.00",
    newPrice: "$45.00",
    free: "18%",
  },
  {
    category: "TOP",
    tooltip: "SALE",
    Dimage: "images/15-1.webp",
    Himage: "images/image_16.png",
    name: "Off-The-Shoulder Blouse",
    oldPrice: "$32.00",
    newPrice: "$40.00",
    free: "20%",
  },
  {
    category: "TOP",
    tooltip: "SALE",
    Dimage: "images/16-1.webp",
    Himage: "images/image_14.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "9%",
  },
  {
    category: "TOP",
    tooltip: "SALE",
    Dimage: "images/20-1.webp",
    Himage: "images/image_13.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "9%",
  },

  {
    category: "T-SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_11.png",
    Himage: "images/image_12.png",
    name: "Mesh Shirt",
    oldPrice: "$55.00",
    newPrice: "$45.00",
    free: "18%",
  },
  {
    category: "T-SHIRT",
    tooltip: "SALE",
    Dimage: "images/image_13.png",
    Himage: "images/image_14.png",
    name: "Off-The-Shoulder Blouse",
    oldPrice: "$32.00",
    newPrice: "$40.00",
    free: "20%",
  },
  {
    category: "T-SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_15.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "9%",
  },
  {
    category: "T-SHIRT",
    tooltip: "SALE",
    Dimage: "images/image_17.png",
    Himage: "images/image_18.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "9%",
  },

  {
    category: "DRESS",
    tooltip: "SALE",
    Dimage: "images/image_25.png",
    Himage: "images/image_24.png",
    name: "Off-The-Shoulder Blouse",
    oldPrice: "$32.00",
    newPrice: "$40.00",
    free: "20%",
  },
  {
    category: "DRESS",
    tooltip: "NEW",
    Dimage: "images/image_23.png",
    Himage: "images/image_20.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "65%",
  },
  {
    category: "DRESS",
    tooltip: "SALE",
    Dimage: "images/image_20.png",
    Himage: "images/image_21.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "22%",
  },
  {
    category: "SETS",
    tooltip: "NEW",
    Dimage: "images/image_14.png",
    Himage: "images/image_15.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "3%",
  },
  {
    category: "SETS",
    tooltip: "SALE",
    Dimage: "images/image_17.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "01%",
  },

  {
    category: "SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_13.png",
    Himage: "images/image_14.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "54%",
  },
  {
    category: "SHIRT",
    tooltip: "SALE",
    Dimage: "images/image_25.png",
    Himage: "images/image_12.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "21%",
  },
  {
    category: "SETS",
    tooltip: "SALE",
    Dimage: "images/image_23.png",
    Himage: "images/image_21.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "24%",
  },
  {
    category: "T-SHIRT",
    tooltip: "SALE",
    Dimage: "images/image_13.png",
    Himage: "images/image_14.png",
    name: "Off-The-Shoulder Blouse",
    oldPrice: "$32.00",
    newPrice: 40.0,
    free: "20%",
  },
  {
    category: "T-SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_15.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "9%",
  },
  {
    category: "SETS",
    tooltip: "SALE",
    Dimage: "images/image_17.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "01%",
  },
  {
    category: "T-SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_15.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: 20.0,
    free: "9%",
  },
  {
    category: "SETS",
    tooltip: "SALE",
    Dimage: "images/image_17.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "01%",
  },
  {
    category: "DRESS",
    tooltip: "SALE",
    Dimage: "images/image_20.png",
    Himage: "images/image_21.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "22%",
  },
  {
    category: "SETS",
    tooltip: "NEW",
    Dimage: "images/image_14.png",
    Himage: "images/image_15.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: 20.0,
    free: "3%",
  },
  {
    category: "SETS",
    tooltip: "SALE",
    Dimage: "images/image_17.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "01%",
  },

  {
    category: "SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_13.png",
    Himage: "images/image_14.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "54%",
  },
  {
    category: "SHIRT",
    tooltip: "SALE",
    Dimage: "images/image_25.png",
    Himage: "images/image_12.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "21%",
  },
  {
    category: "SETS",
    tooltip: "SALE",
    Dimage: "images/image_23.png",
    Himage: "images/image_21.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: "$20.00",
    free: "24%",
  },
  {
    category: "T-SHIRT",
    tooltip: "SALE",
    Dimage: "images/image_13.png",
    Himage: "images/image_14.png",
    name: "Off-The-Shoulder Blouse",
    oldPrice: "$32.00",
    newPrice: "$40.00",
    free: "20%",
  },
  {
    category: "T-SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_15.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: 20.0,
    free: "9%",
  },
  {
    category: "SETS",
    tooltip: "SALE",
    Dimage: "images/image_17.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: 20,
    free: "01%",
  },
  {
    category: "T-SHIRT",
    tooltip: "NEW",
    Dimage: "images/image_15.png",
    Himage: "images/image_16.png",
    name: "Kinimo Sleve Top",
    oldPrice: "$12.00",
    newPrice: 20.0,
    free: "9%",
  },
];

export default allProducts;
